In [1]:
import numpy as np

M = 5
N = 10
X = np.random.randn(M, N)

covariance_matrix = np.cov(X)
correlation_matrix = np.corrcoef(X)

print(covariance_matrix)
print(correlation_matrix)

[[ 1.58947758  0.22543224 -0.94146372 -0.47670936  0.06309526]
 [ 0.22543224  0.19789902 -0.04994569  0.01577299 -0.01918746]
 [-0.94146372 -0.04994569  1.30074977  0.27302402 -0.07001637]
 [-0.47670936  0.01577299  0.27302402  1.00213236 -0.23249097]
 [ 0.06309526 -0.01918746 -0.07001637 -0.23249097  0.43528814]]
[[ 1.          0.40194534 -0.65475603 -0.37771474  0.07585446]
 [ 0.40194534  1.         -0.09844175  0.03541845 -0.06537432]
 [-0.65475603 -0.09844175  1.          0.23913406 -0.09304955]
 [-0.37771474  0.03541845  0.23913406  1.         -0.35201011]
 [ 0.07585446 -0.06537432 -0.09304955 -0.35201011  1.        ]]
